# apiVersion: apps/v1
# kind: Deployment  # or StatefulSet
# metadata:
#   name: talend-remote-engine-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: talend-remote-engine
#   template:
#     metadata:
#       labels:
#         app: talend-remote-engine
#     spec:
#       initContainers:
#       - name: setup-talend-remote-engine
#         image: trabelsii/faltena-remote-engine:latest
#         command: ["feature:install wrapper", "wrapper:install -n Talend-Remote-Engine"]  # Replace with the commands you need to execute
#         # Add other init container configurations as needed
#       containers:
#       - name: talend-remote-engine-container
#         image: trabelsii/faltena-remote-engine:latest
#         # Add other container configurations like ports, resources, environment variables, etc.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talend-remote-engine-deployment
spec:
  replicas: 1   # Set the desired number of replicas (you can adjust this number based on your needs)
  selector:
    matchLabels:
      app: talend-remote-engine
  template:
    metadata:
      labels:
        app: talend-remote-engine
    spec:
      containers:
      - name: talend-remote-engine-container-alt
        image: trabelsii/talend-remote-engine-alt-2:1.0
        ports:
        - containerPort: 8040  # Assuming the container listens on port 8040
---
apiVersion: v1
kind: Service
metadata:
  name: talend-remote-engine
spec:
  selector:
    app: talend-remote-engine
  ports:
  - protocol: TCP
    port: 8040
    targetPort: 8040


